version: '2'
services:


  ## rss
  rs01a:
    build: ./
    container_name: rs01a
    network_mode: bridge
    command: '--port 27017 --replSet rs01  --smallfiles --oplogSize 16 --enableMajorityReadConcern false --keyFile /scripts/test.key'
    ports:
      - "0.0.0.0:27117:27017"
    volumes:
      - ./data/rs01a/db:/data/db
      - ./data/rs01a/configdb:/data/configdb
    extra_hosts:
      - "basehost:192.168.1.6"

  rs01b:
    build: ./
    container_name: rs01b
    network_mode: bridge
    command: '--port 27017 --replSet rs01  --smallfiles --oplogSize 16 --enableMajorityReadConcern false --keyFile /scripts/test.key'
    ports:
      - "0.0.0.0:27118:27017"
    volumes:
      - ./data/rs01b/db:/data/db
      - ./data/rs01b/configdb:/data/configdb
    extra_hosts:
      - "basehost:192.168.1.6"

  rs01c:
    build: ./
    container_name: rs01c
    network_mode: bridge
    command: '--port 27017 --replSet rs01  --smallfiles --oplogSize 16 --enableMajorityReadConcern false --keyFile /scripts/test.key'
    ports:
      - "0.0.0.0:27119:27017"
    volumes:
      - ./data/rs01c/db:/data/db
      - ./data/rs01c/configdb:/data/configdb
    extra_hosts:
      - "basehost:192.168.1.6"
