version: '3'

services:
  mongo-rs0-1:
    image: 'mongo'
    container_name: mongo-rs0-1
    command: --replSet rs0
    command: --config ./conf/mongo.conf
    ports:
      - '27017:27017' # left is computer's port right side is docker internal port
    volumes:
      - ./data/mongo-rs0-1/data:/data/db
      - ./test.key:/conf/test.key
      - ./mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js
      - ./setup/mongoSetup.js:/mongoSetup.js
    depends_on:
      - 'mongo-rs0-2'
      - 'mongo-rs0-3'

  mongo-rs0-2:
    image: 'mongo'
    container_name: mongo-rs0-2
    command: --replSet rs0
    command: --config ./conf/mongo.conf
    ports:
      - '27018:27017'
    volumes:
      - ./data/mongo-rs0-2/data:/data/db
      - ./test.key:/conf/test.key
      - ./mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js

  mongo-rs0-3:
    image: 'mongo'
    container_name: mongo-rs0-3
    command: --replSet rs0
    command: --config ./conf/mongo.conf
    ports:
      - '27019:27017'
    volumes:
      - ./data/mongo-rs0-3/data:/data/db
      - ./test.key:/conf/test.key
      - ./mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js
