version: '3'

services:
  # mongo rs0
  mongo-rs0-1:
    image: 'mongo'
    container_name: mongo-rs0-1
    command: --config ./conf/mongo.conf
    ports:
      - '27217:27017' # left is computer's port right side is docker internal port
    volumes:
      - ./data/mongo-rs0-1/data:/data/
      - ./test.key:/conf/test.key
      - ./rs0_mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js
      - ./setup/rs0_mongoSetup.js:/mongoSetup.js
    depends_on:
      - 'mongo-rs0-2'
      - 'mongo-rs0-3'

  mongo-rs0-2:
    image: 'mongo'
    container_name: mongo-rs0-2
    command: --config ./conf/mongo.conf
    ports:
      - '27218:27017'
    volumes:
      - ./data/mongo-rs0-2/data:/data/
      - ./test.key:/conf/test.key
      - ./rs0_mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js

  mongo-rs0-3:  # arbiterOnly
    image: 'mongo'
    container_name: mongo-rs0-3
    command: --config ./conf/mongo.conf
    ports:
      - '27219:27017'
    volumes:
      - ./data/mongo-rs0-3/data:/data/
      - ./test.key:/conf/test.key
      - ./rs0_mongo.conf:/conf/mongo.conf

  # # mongo rs1

  mongo-rs1-1:
    image: 'mongo'
    container_name: mongo-rs1-1
    command: --config ./conf/mongo.conf
    ports:
      - '27117:27017' # left is computer's port right side is docker internal port
    volumes:
      - ./data/mongo-rs1-1/data:/data/
      - ./test.key:/conf/test.key
      - ./rs1_mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js
      - ./setup/rs1_mongoSetup.js:/mongoSetup.js
    depends_on:
      - 'mongo-rs1-2'
      - 'mongo-rs1-3'

  mongo-rs1-2:
    image: 'mongo'
    container_name: mongo-rs1-2
    command: --config ./conf/mongo.conf
    ports:
      - '27118:27017'
    volumes:
      - ./data/mongo-rs1-2/data:/data/
      - ./test.key:/conf/test.key
      - ./rs1_mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js

  mongo-rs1-3:  # arbiterOnly
    image: 'mongo'
    container_name: mongo-rs1-3
    command: --config ./conf/mongo.conf
    ports:
      - '27119:27017'
    volumes:
      - ./data/mongo-rs1-3/data:/data/
      - ./test.key:/conf/test.key
      - ./rs1_mongo.conf:/conf/mongo.conf


  # # mongo rs1

  mongo-rscfg-1:
    image: 'mongo'
    container_name: mongo-rscfg-1
    command: --configsvr --config ./conf/mongo.conf
    ports:
      - '27817:27017' # left is computer's port right side is docker internal port
    volumes:
      - ./data/mongo-rscfg-1/data:/data/
      - ./test.key:/conf/test.key
      - ./rscfg_mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js
      - ./setup/rscfg_mongoSetup.js:/mongoSetup.js
    depends_on:
      - 'mongo-rscfg-2'
      - 'mongo-rscfg-3'

  mongo-rscfg-2:
    image: 'mongo'
    container_name: mongo-rscfg-2
    command: --configsvr --config ./conf/mongo.conf
    ports:
      - '27818:27017'
    volumes:
      - ./data/mongo-rscfg-2/data:/data/
      - ./test.key:/conf/test.key
      - ./rscfg_mongo.conf:/conf/mongo.conf
      - ./setup/dbSetup.js:/dbSetup.js

  mongo-rscfg-3:
    image: 'mongo'
    container_name: mongo-rscfg-3
    command: --configsvr --config ./conf/mongo.conf
    ports:
      - '27819:27017'
    volumes:
      - ./data/mongo-rscfg-3/data:/data/
      - ./test.key:/conf/test.key
      - ./rscfg_mongo.conf:/conf/mongo.conf

  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongo-rscfg-1
      - mongo-rscfg-2
      - mongo-rscfg-3
    command: mongos --configdb rscfg/mongo-rscfg-1:27017,mongo-rscfg-2:27017,mongo-rscfg-3:27017 --port 27917   --keyFile /conf/test.key
    ports:
      - 27017:27917
    volumes:
      - ./test.key:/conf/test.key
